---
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']
      
node_exporter_version: "1.7.0"
node_exporter_download_url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"

node_exporter_user: "node_exporter"
node_exporter_group: "node_exporter"

node_exporter_data_dir: "/var/lib/node_exporter"
node_exporter_tmp_dir: "/tmp"
node_exporter_install_path: "/usr/local/bin/node_exporter"
