---
- name: Create Node Exporter user
  ansible.builtin.user:
    name: "{{ node_exporter_user }}"
    system: yes
    shell: /sbin/nologin
    create_home: no

- name: Create directories for Node Exporter
  ansible.builtin.file:
    path: "{{ node_exporter_data_dir }}"
    state: directory
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"
    mode: '0755'

- name: Download Node Exporter
  ansible.builtin.get_url:
    url: "{{ node_exporter_download_url }}"
    dest: "{{ node_exporter_tmp_dir }}/node_exporter.tar.gz"
    mode: '0644'

- name: Extract Node Exporter
  ansible.builtin.unarchive:
    src: "{{ node_exporter_tmp_dir }}/node_exporter.tar.gz"
    dest: "{{ node_exporter_tmp_dir }}"
    remote_src: yes
    creates: "{{ node_exporter_tmp_dir }}/node_exporter-{{ node_exporter_version }}.linux-amd64"

- name: Move Node Exporter binary
  ansible.builtin.copy:
    src: "{{ node_exporter_tmp_dir }}/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
    dest: "{{ node_exporter_install_path }}"
    mode: '0755'
    remote_src: yes

- name: Clean up temporary files
  ansible.builtin.file:
    path: "{{ node_exporter_tmp_dir }}/node_exporter-{{ node_exporter_version }}.linux-amd64"
    state: absent
