---
- name: Create Prometheus user
  ansible.builtin.user:
    name: "{{ prometheus_user }}"
    system: yes
    shell: /sbin/nologin

- name: Create directories for Prometheus
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: prometheus
    mode: '0755'
  loop:
    - /etc/prometheus
    - /var/lib/prometheus

- name: Download Prometheus
  ansible.builtin.get_url:
    url: "{{ prometheus_download_url }}"
    dest: "/tmp/prometheus.tar.gz"
    mode: '0644'

- name: Extract Prometheus
  ansible.builtin.unarchive:
    src: "/tmp/prometheus.tar.gz"
    dest: "/tmp"
    remote_src: yes
    creates: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64"

- name: Move Prometheus binaries
  ansible.builtin.copy:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
    dest: "{{ prometheus_install_dir }}/{{ item }}"
    mode: '0755'
    remote_src: yes
  loop:
    - prometheus
    - promtool

- name: Clean up temporary files
  ansible.builtin.file:
    path: "/tmp/prometheus-2.45.0.linux-amd64"
    state: absent
    
- name: Ensure Prometheus directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: prometheus
    mode: '0755'
  loop:
    - "{{ prometheus_config_dir }}"
    - "{{ prometheus_data_dir }}"

- name: Set permissions for Prometheus directories
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ prometheus_user }}"
    group: prometheus
    recurse: yes
  loop:
    - "{{ prometheus_config_dir }}"
    - "{{ prometheus_data_dir }}"