---
- name: Deploy Prometheus systemd service
  ansible.builtin.template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    owner: root
    group: root
    mode: '0644'
  notify: Reload systemd

- name: Enable and start Prometheus service
  ansible.builtin.systemd:
    name: prometheus
    enabled: yes
    state: started